        //! `osp-cli-foundation` is the single-crate staging area for the future root
        //! `src/` layout.
        //!
        //! The internal implementation still mirrors the old workspace split under
        //! `osp_*` module names, but consumers should start preferring the stable
        //! top-level modules exported here:
        //!
        //! - [`app`] for the main CLI entrypoints and stateful host surface
        //! - [`config`] for configuration types and resolution
        //! - [`core`] for shared output, row, and runtime types
        //! - [`dsl`] for pipeline parsing and execution
        //! - [`ui`] for rendering and message formatting
        //! - [`repl`] for REPL engine types
        //! - [`completion`] for command/completion tree types
        //! - [`plugin`] for plugin discovery/dispatch management
        //! - [`api`], [`ports`], and [`services`] for the service/client layer
        //!
        //! Most `osp_*` modules remain public for now as compatibility shims while the
        //! crate is still transitioning away from the generated mirror layout.
        //
        // Generated by scripts/build-foundation-crate.py.
        // Edit the workspace crates first, then regenerate this prototype.

        #[doc(hidden)]
pub mod osp_core;
#[doc(hidden)]
pub mod osp_config;
#[doc(hidden)]
pub mod osp_dsl;
#[doc(hidden)]
pub mod osp_ports;
#[doc(hidden)]
pub mod osp_api;
#[doc(hidden)]
pub mod osp_services;
mod osp_ui;
#[doc(hidden)]
pub mod osp_completion;
#[doc(hidden)]
pub mod osp_repl;
#[doc(hidden)]
pub mod osp_cli;

        pub mod app;
        pub mod runtime;
        pub mod config;
        pub mod core;
        pub mod dsl;
        pub mod ports;
        pub mod api;
        pub mod services;
        pub mod ui;
        pub mod completion;
        pub mod repl;
        pub mod cli;
        pub mod plugin;
        pub mod prelude;

        pub use crate::app::{App, AppBuilder, AppRunner, run_from, run_process};

        #[cfg(test)]
        mod tests;
