        //! `osp-cli-foundation` is the single-crate staging area for the future root
        //! `src/` layout.
        //!
        //! The internal implementation still mirrors the old workspace split under
        //! `osp_*` module names, but consumers should start preferring the stable
        //! top-level modules exported here:
        //!
        //! - [`app`] for the main CLI entrypoints and stateful host surface
        //! - [`config`] for configuration types and resolution
        //! - [`core`] for shared output, row, and runtime types
        //! - [`dsl`] for pipeline parsing and execution
        //! - [`ui`] for rendering and message formatting
        //! - [`repl`] for REPL engine types
        //! - [`completion`] for command/completion tree types
        //! - [`api`], [`ports`], and [`services`] for the service/client layer
        //!
        //! The `osp_*` modules remain public for now as compatibility shims while the
        //! crate is still transitioning away from the generated mirror layout.
        //
        // Generated by scripts/build-foundation-crate.py.
        // Edit the workspace crates first, then regenerate this prototype.

        #[doc(hidden)]
pub mod osp_core;
#[doc(hidden)]
pub mod osp_config;
#[doc(hidden)]
pub mod osp_dsl;
#[doc(hidden)]
pub mod osp_ports;
#[doc(hidden)]
pub mod osp_api;
#[doc(hidden)]
pub mod osp_services;
#[doc(hidden)]
pub mod osp_ui;
#[doc(hidden)]
pub mod osp_completion;
#[doc(hidden)]
pub mod osp_repl;
#[doc(hidden)]
pub mod osp_cli;

        pub mod app {
            //! Main host-facing entrypoints and stateful runtime surfaces.

            pub use crate::osp_cli::state;
            pub use crate::osp_cli::{Cli, classify_exit_code, render_report_message, run_from, run_process};
        }

        pub mod config {
            //! Configuration loading, resolution, schema, and persistence.

            pub use crate::osp_config::*;
        }

        pub mod core {
            //! Shared output, row, runtime, and plugin protocol types.

            pub use crate::osp_core::*;
        }

        pub mod dsl {
            //! DSL parsing, stage metadata, and pipeline execution.

            pub use crate::osp_dsl::*;
        }

        pub mod ports {
            //! Port traits and data-shaping helpers used by services and APIs.

            pub use crate::osp_ports::*;
        }

        pub mod api {
            //! Higher-level API/client adapters built on the shared ports layer.

            pub use crate::osp_api::*;
        }

        pub mod services {
            //! Service-style command execution helpers over config, DSL, and ports.

            pub use crate::osp_services::*;
        }

        pub mod ui {
            //! Rendering, layout, document, and message formatting surfaces.

            pub use crate::osp_ui::*;
        }

        pub mod completion {
            //! Completion tree, engine, and suggestion model types.

            pub use crate::osp_completion::*;
        }

        pub mod repl {
            //! REPL engine and prompt/history types.

            pub use crate::osp_repl::*;
        }

        pub mod cli {
            //! CLI-specific pipeline and state helpers still owned by the host layer.

            pub use crate::osp_cli::{pipeline, state};
        }

        pub mod prelude {
            //! Small convenience surface for embedding the app without importing the full module tree.

            pub use crate::app::{Cli, run_from, run_process};
            pub use crate::core::output::{ColorMode, OutputFormat, RenderMode, UnicodeMode};
            pub use crate::ui::RenderSettings;
        }

        pub use crate::app::{Cli, run_from, run_process};

        #[cfg(test)]
        mod tests {
            use crate::core::output::OutputFormat;

            #[test]
            fn stable_top_level_surface_exposes_primary_entrypoints_and_types_unit() {
                let _run_from = |args: Vec<&str>| crate::app::run_from::<Vec<&str>, &str>(args);
                let _run_process =
                    |args: Vec<&str>| crate::app::run_process::<Vec<&str>, &str>(args);
                let _cli_type: Option<crate::app::Cli> = None;
                let _format = OutputFormat::Json;
                let _settings = crate::ui::RenderSettings::test_plain(OutputFormat::Table);
            }

            #[test]
            fn legacy_osp_namespaces_still_exist_during_transition_unit() {
                let _settings = crate::osp_ui::RenderSettings::test_plain(OutputFormat::Table);
                let _format = crate::osp_core::output::OutputFormat::Json;
                let _cli_type: Option<crate::osp_cli::Cli> = None;
            }
        }
